version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: hello
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql


  spring-boot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: hello
